# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100)
#' rnC
#' }
#' @export
gibbs_cpp <- function(N) {
    .Call('_StatComp21031_gibbs_cpp', PACKAGE = 'StatComp21031', N)
}

